### ISSUE TITLE
Question - Is remoteAudio a good starting place for a hack project of mine?

### ISSUE THREAD

**Issue by nickjackson** [dh1tw/remoteAudio#12]
Hello @dh1tw

This is awesome. I’ve just tried it out and works very smoothly.

I’ve been looking into building a LAN based p2p matrix intercom as a hack project in Go. I was googling around to see what else existed and just found this project.

My idea was to have a single program, “a peer” that would...
- connect via portaudio to its sound interface
- discover other peers (via gossip or some registry on the network)
- host a webpage that could connect to other peers and mix levels (similar to the remoteAudio client)

Do you think your project is a good starting point, or do you think I should look elsewhere to build this kind of thing?

Thanks,
Nick.

**Comment by dh1tw** [comment]
Hi @nickjackson,

I'm not sure if forking remoteAudio for this purpose is a good idea, but I'm sure it can act as a reference on how to implement portaudio and send stuff over the network :-) 

As for selecting the transport protocol it depends very much on your attempted mode of operation. I choose MQTT since some of the remoteAudio clients might be behind a NAT firewall (e.g. when the server is connected through a 3G/4G stick). Since all instances of remoteAudio (server and clients) connect to a publicly accessible MQTT broker, it can be operated from anywhere.
SIP/STUN might be one way to solve this problem as it provides some means to solve this problem, but it doesn't always work. Sometimes it even requires to open ports on your router which I think is an awful thing.

If you are just in a LAN any P2P protocol will work. 

As for discovering other peers your use case scenario also will heavily influence the solution. 
If all clients are in the same network you could use multicast or a registry service like [consul](https://www.consul.io) which provides a K/V store which you can set explicit watchers. There is also a [consul client for golang](https://github.com/hashicorp/consul/tree/master/api) which I recommend to check out.

If you are on the public internet it might be worthwhile to write a small registry service with a REST endpoint.

If you want to mix the audio for a conference kind of feature it get's a bit more tricky, and you will have to apply some math.

I hope this provides some guidance ;-)

Tobias
