### ISSUE TITLE
Specify Transition Protocol on Windows

### ISSUE THREAD

**Issue by dgorbunov** [dh1tw/remoteAudio#15]
Is specifying transitional protocol implemented on windows? I cant start the client because it wants me to specify the transition protocol. It tells me to check --help, which seems to be missing things about the transition protocol. You seem to define it in 'Getting Started' as `remoteAudio server mqtt`, but this command doesnt work on Windows? Am I doing something wrong? How do I get it running?

**Comment by dh1tw** [comment]
Hey, 
please note that the transport layer has changed in version 0.3.0 from MQTT to NATS. You will need to install a [NATS broker (gnatsd)](https://nats.io/download/nats-io/gnatsd). 
There is more information about the changes in the [release note of the alpha releases](https://github.com/dh1tw/remoteAudio/releases). The reason why you have to choice a transport protocol is due to the architecture of the software. It is pretty easy to add additional transport protocols like plain TCP, UDP, GRPC, ... etc in the future (if somebody needs it).
I have received positive feedback from my testers about 0.3.0.alpha11, It runs stable.
I'm currently (when time allows) finishing the last features for 0.3.0.
