### ISSUE TITLE
"old" and "new" seem to inter work

### ISSUE THREAD

**Issue by K6TD** [dh1tw/remoteAudio#29]
Description starting with release 0.5.0 says the binary won't wire with prior releases.   I found they do seem to inter work.

Not really a bug.  Interesting, none the less.

**Comment by dh1tw** [comment]
Hey Kevin, indeed - in principal there is a good chance that it still might work. However, since I changed the [protobuf](https://developers.google.com/protocol-buffers/) serialization library, I found a few edge cases where I ran into problems. Therefore I highly recommend to update all instances to the latest version - or maintain consistently on the same legacy version.
